version: "3.1"
services:
  app:
    container_name: affection-captcha-bot
    build: app
    restart: unless-stopped
    volumes:
      - "./app:/app"
      - "./data:/data"
    environment:
      - DATA_FOLDER=/data
    command: ['python', 'main.py']
    env_file:
      - ./app/.env